name: test_app_2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#Localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

#Navigation
  auto_route: ^8.2.0

#UI
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#Code generation
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/happy.png"

flutter_intl:
  enabled: true
  class_name: Localized
  main_locale: ru
  arb_dir: lib/src/common/localization/intl
  output_dir: lib/src/common/localization
  use_deffered_loading: false


